import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic';
import Link from 'next/link'

const Pesquisa = dynamic(() => import('./components/pesquisa'))

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Pesquisa className="font-geisSans; text-white; font-bold">
        <Link href="/form">Formulário</Link>
        <Link href="/test">Test</Link>
      </Pesquisa>

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
